version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/main/resources/html:/tmp/html
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    image: 'app:1.0'
    build: ./
    container_name: app